### ISSUE TITLE
Handlebar Helper Changes

### ISSUE THREAD

**Issue by vigoren** [vttred/ose#158]
Bit of a different issue.
I make a module that uses the HandlebarHelper gt that is included with FoundryVTTs code (foundry.js line 5082). This system includes its [own version of that HandlebarHelper](https://github.com/vttred/ose/blob/main/src/module/helpers.js#L9) but your version is greater than or equal too instead of just greater than.

FoundryVTTs code also includes a greater than or equal to helper, gte. I am requesting that your code be updated to use the gte instead of your own gt implementation. From my quick scan of your template files I only found 1 template that users the gt helper and that is the [character-header](https://github.com/vttred/ose/blob/main/src/templates/actors/partials/character-header.html#L39)

I think these were added before Foundry added their own so it is more of a legacy reason they are in the systems code.
My reasoning for this change is the system overwrites that HandlebarHelper and as a result some information in my module is showing when it shouldn't.

I can also make the change if you would prefer.

Thanks!

**Comment by anthonyronda** [comment]
Nice catch, and thanks so much for doing the legwork on finding where it's used. I can fix this one quickly!

**Comment by anthonyronda** [comment]
Sorry this took so long, it completely slipped under the radar because I marked it as a character-sheet enhancement without any kind of priority indicator 🤦I do try to make conflicts with modules more of a priority so I'll make sure to add a label for that for future issues.

Still testing this change but expect the fix in the next release!
