### ISSUE TITLE
Shopping cart numbers off

### ISSUE THREAD

**Issue by aramyle** [vttred/ose#193]
Any items with a quantity (rations, rope, etc.) are multiplied by the quantity for the price. Rations costs 105gp instead of the 15gp it should because a ration comes with 7/7.

**Comment by anthonyronda** [comment]
Thanks for reporting that because I don't have an issue with that yet. Was reported in Discord, and it's indeed an unintended behavior of the intended implementation.

My current fix, provided I can confirm it covers all cases, is to only multiply the cost when there isn't a maximum quantity for the item.
