### ISSUE TITLE
More than 1 "Shield" items is not supported

### ISSUE THREAD

**Issue by odhinn33** [vttred/ose#237]
### What happened?

I have a character with one shield and 1 ring of protection, each of them applies 1 bonus to the AC. It only works with one and the second item is ignored. Please fix, thanks.

### What is the expected behaviour?

To add bonuses

### Foundry VTT Core Version

Tested in v9 and v10

### Old-School Essentials Core Version

even 1.6.3 has the issue

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
We are tracking this as an enhancement request in #90.

The way armor "replaces" rather than was a design decision from a previous maintainer to keep the implementation of armor simple (active effects did not exist at the time the system was designed). I do intend to implement this change, and you can follow #90 to see more information when it becomes available
