### ISSUE TITLE
OSE v1.6.0 Broken

### ISSUE THREAD

**Issue by seanwilliams1964** [vttred/ose#238]
Hey team, I haven't looked to see if anything was reported, but I am running Foundry VTT version 9 over on Forge-Vtt.com. Suddenly our Attributes page was broken for all of our character sheets. All stats are either 0 or NaN. Additionally, none of the clickables work from within the form.

I know you updated it to be Foundry v10 compatible, but apparently it broke the latest v9.

Thanks!

**Comment by anthonyronda** [comment]
@seanwilliams1964 please uninstall ose 1.6.0 and reinstall ose 1.5.1.

Due to a process error, 1.6.0 was temporarily available on V9 for a short time. 1.6.0 is not compatible with Foundry VTT V9

I've heard that OSE is currently not working on The Forge if you're in Foundry V9, and I'm working with the good people at The Forge to get that resolved for you. For now the workaround is to install version 1.5.1 of OSE (V9 only!) using the manifest link. Thanks!
