### ISSUE TITLE
Notes tab missing

### ISSUE THREAD

**Issue by WallaceMcGregor** [vttred/ose#25]
Whe you select a spell caster PC, the spell tab appear but the notes tab disappear.

**Comment by justinthejaguar** [comment]
What version are you on? It works as expected in the latest build.
![image](https://user-images.githubusercontent.com/38022481/149662889-d173520a-c308-4c4c-a743-88714d79cc5b.png)

**Comment by WallaceMcGregor** [comment]
I'm on the last one, but an old Foundry version. I don't know if could be that.

![chrome_2022-01-16_18-03-00](https://user-images.githubusercontent.com/17795541/149670147-9120f267-aa84-4e66-9fee-127aa36c3e93.jpg)

![chrome_2022-01-16_18-05-44](https://user-images.githubusercontent.com/17795541/149670161-dd3d2410-5d96-48ad-938c-4964c56d22da.jpg)

**Comment by anthonyronda** [comment]
I can reproduce this bug in Spanish for 0.8.9. It does not occur in English for 0.8.9. The difference in tab name length between the two languages is the root cause.

For some reason V9 renders the same css differently, and the tabs are much more spaced out. As such this is not an issue in V9 with English or Spanish. Other languages not tested.

I'd like to resolve this in 0.8.9 if at all possible, but I'll have to hunt down reasons why these are rendered differently.
