### ISSUE TITLE
Remove v9 compatibility code

### ISSUE THREAD

**Issue by maschill92** [vttred/ose#261]
### New Feature or Changed Behaviour

Current releases moving forward will not support v9. That being the case we can remove all v9 compatibility code.

### Why?

The code is effectively dead and now technical debt. It has no reason to exist.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
All "V9 compatibility code" should now be removed. 

I'm aware of one case where TextEditor.enrichHTML is used synchronously instead of the new async default behavior. Although synchronous enrichHTML is deprecated, we plan to refactor the affected feature at a later time (the `async: false` flag is not exactly compatibility code, anyway)
