### ISSUE TITLE
Equip button on the monsters equipment tab cannot be toggled

### ISSUE THREAD

**Issue by crazyclausewitz** [vttred/ose#34]
The equip button for items on the monsters equipment tab cannot be toggled. Since the button is rather pointless, consider removing it.

**Comment by freohr** [comment]
I can reproduce it for Armor in the inventory tab (weapons don't show up in the inventory tab)

**Comment by engleback** [comment]
What would happen if armour was enabled? Would this improve AC? In some cases this may be desirable, such as a Bandit Leader wearing plate, etc?

**Comment by anthonyronda** [comment]
I was going to fix this tonight but I'll wait until next week. I'm not ready to make a design decision like removing the equip button because it would mean creating a new inventory sheet (monsters currently borrow `character-inventory-tab.html`)

Making the equip toggle functional is easy.

> What would happen if armour was enabled? Would this improve AC? In some cases this may be desirable, such as a Bandit Leader wearing plate, etc?

Do any rules modules have any suggestion either way about this? I love the opportunity to spice up a compendium monster with new gear. Currently we don't compute AC for monsters, it's a static value, but it could easily be done. I would want a way to show both values on the attributes tab.

**Comment by anthonyronda** [comment]
> Once you start computing AC for monsters, you will have to equip every monster with appropriate armor to show the desired AC value. Which means you have to redo the monster compendium.

I didn't make my intentions clear. I have no interest in giving monsters armor in `ose-content` *unless* that monster's statblock mentions armor, in which case we really ought to fix that. This would just be a value-add for monsters in need of a little extra pizzazz for the encounter you're putting together. That said, if there's ever a compendium update where we can calculate the intended value for a new property, I intend to write a migration so all of the world's existing documents also benefit from the change.

**Comment by crazyclausewitz** [comment]
I can see how this will work for a shield but not for leather, chainmail or plate. That is unless you treat the monsters AC as its natural armor and add the extra armor on top of it, which I fear will be confusing for a lot of people. I already can see people creating "malus" armor to get the AC right :)
There is actually only the Trader that explicitly mentions the armor worn. And then Brigand, Buccaneer, Dervish, Nomad and Pirate for overall troop composition.

**Comment by anthonyronda** [comment]
Ultimately decided to make an if statement that only renders the button for characters.

Mind you this is a change that affects the player character sheet. I'm currently tracking all changes to the player character sheet as part of the character sheet redesign. That's why I've added the character sheet tag as well.
